/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.Color;
import javax.swing.JFrame;

/**
 *
 * @author yustitia arofa
 */
public class view extends javax.swing.JFrame {

    /**
     * Creates new form view
     */
    int pindahx;
    int pindahy;
    public view() {
        initComponents();
        bayangan.setBackground(new Color(0, 0, 0, 200));
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bayangan = new javax.swing.JPanel();
        jPasswordField1 = new javax.swing.JPasswordField();
        nama = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        register = new javax.swing.JButton();
        login = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        kecil = new javax.swing.JLabel();
        tutup = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bayangan.setBackground(new java.awt.Color(44, 62, 80));
        bayangan.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        bayangan.setForeground(new java.awt.Color(240, 240, 240));
        bayangan.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                bayanganMouseDragged(evt);
            }
        });
        bayangan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bayanganMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                bayanganMousePressed(evt);
            }
        });
        bayangan.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPasswordField1.setBackground(new java.awt.Color(44, 62, 80));
        jPasswordField1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPasswordField1.setForeground(new java.awt.Color(255, 255, 255));
        jPasswordField1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        bayangan.add(jPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, 250, 30));

        nama.setBackground(new java.awt.Color(44, 62, 80));
        nama.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        nama.setForeground(new java.awt.Color(255, 255, 255));
        nama.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        nama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namaActionPerformed(evt);
            }
        });
        bayangan.add(nama, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, 250, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\yustitia arofa\\Downloads\\icons8-user-48.png")); // NOI18N
        bayangan.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 40, 40));

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\yustitia arofa\\Downloads\\icons8-key-2-48.png")); // NOI18N
        bayangan.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 50, 40));

        register.setBackground(new java.awt.Color(0, 153, 255));
        register.setText("REGISTER");
        bayangan.add(register, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 270, 120, 40));

        login.setBackground(new java.awt.Color(0, 204, 0));
        login.setText("LOGIN");
        login.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        bayangan.add(login, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 270, 120, 40));

        jLabel4.setBackground(new java.awt.Color(52, 73, 94));
        jLabel4.setFont(new java.awt.Font("Segoe UI Black", 3, 48)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 153, 255));
        jLabel4.setText("Selamat ");
        bayangan.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 250, 70));

        jLabel5.setFont(new java.awt.Font("Source Sans Pro Black", 3, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("datang");
        bayangan.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 70, 130, 40));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("silahkan masukan Username dan password anda ");
        bayangan.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, 280, 20));

        kecil.setFont(new java.awt.Font("Tekton Pro", 1, 80)); // NOI18N
        kecil.setForeground(new java.awt.Color(51, 153, 255));
        kecil.setLabelFor(this);
        kecil.setText("-");
        kecil.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        kecil.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                kecilMouseClicked(evt);
            }
        });
        bayangan.add(kecil, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 0, 30, 40));
        kecil.getAccessibleContext().setAccessibleParent(this);

        tutup.setFont(new java.awt.Font("Tekton Pro", 1, 36)); // NOI18N
        tutup.setForeground(new java.awt.Color(51, 153, 255));
        tutup.setLabelFor(this);
        tutup.setText("X");
        tutup.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tutup.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tutupMouseClicked(evt);
            }
        });
        bayangan.add(tutup, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 0, 20, 40));

        getContentPane().add(bayangan, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 350, 470));

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\yustitia arofa\\Pictures\\png\\1.jpg")); // NOI18N
        jLabel2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jLabel2MouseDragged(evt);
            }
        });
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 350, 470));

        setSize(new java.awt.Dimension(349, 468));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void namaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namaActionPerformed

    private void tutupMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tutupMouseClicked
        System.exit(0);
    }//GEN-LAST:event_tutupMouseClicked

    private void kecilMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kecilMouseClicked
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_kecilMouseClicked

    private void bayanganMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bayanganMouseClicked
    
    }//GEN-LAST:event_bayanganMouseClicked

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked

    }//GEN-LAST:event_formMouseClicked

    private void jLabel2MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseDragged
    
    }//GEN-LAST:event_jLabel2MouseDragged

    private void bayanganMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bayanganMouseDragged
     int x = evt.getXOnScreen();
     int  y = evt.getYOnScreen();
     this.setLocation(x - pindahx ,y - pindahy);
        System.out.println(x+","+y);
    }//GEN-LAST:event_bayanganMouseDragged

    private void bayanganMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bayanganMousePressed
      pindahx = evt.getX();
      pindahy = evt.getY();

    }//GEN-LAST:event_bayanganMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(view.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(view.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(view.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(view.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new view().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bayangan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JLabel kecil;
    private javax.swing.JButton login;
    private javax.swing.JTextField nama;
    private javax.swing.JButton register;
    private javax.swing.JLabel tutup;
    // End of variables declaration//GEN-END:variables
}
